name: Deploy to Node.js Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Navigate to js folder and install dependencies
        run: |
          cd js  # Change directory to the 'js' folder where package.json is located
          npm install  # Install dependencies from package.json inside 'js' folder

      - name: Run krish-ai.js
        run: |
          echo "Running krish-ai.js script"
          node js/krish-ai.js  # Ensure to run it with the correct path
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
