name: Deploy to Node.js Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install  # Install all dependencies, including jsdom

      - name: Run krish-ai.js
        run: |
          echo "Running krish-ai.js script"
          node js/krish-ai.js  # Run your script
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
